<?xml version="1.0"?>
<!DOCTYPE table [
	<!ELEMENT table (title,description,operation+)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT operation (desc,res*)>
			<!ATTLIST operation start NMTOKEN #REQUIRED>
			<!ATTLIST operation dt NMTOKEN #REQUIRED>
			<!ATTLIST operation sdesc ( no_tm|no_bm3|bad_tm|bad_data|no_p1|no_p2|no_p3|no_p4|hxonly|no_p12|no_p34|no_p23|no_p32|no_10Hz_filt|no_spin_fits|spec_bias|bad_bias|bad_lx|bad_hx|info|TBD ) #REQUIRED>
			<!ATTLIST operation plan ( yes | no ) #REQUIRED>
			<!ATTLIST operation c1 ( yes | no ) "no">
			<!ATTLIST operation c2 ( yes | no ) "no">
			<!ATTLIST operation c3 ( yes | no ) "no">
			<!ATTLIST operation c4 ( yes | no ) "no">
			<!ELEMENT desc (#PCDATA)>
			<!ELEMENT res (link*)>
			<!ELEMENT link (#PCDATA)>
			<!ATTLIST link href CDATA #REQUIRED>
]>
<!--
There are four columns in the output:
START    DT    PLAN   SDESC
START   Start time of the anomaly, ISO time string
DT      Length of the anomaly in sec. -1 means infinity. -157 means TDB.
SDESC   Short description of the anomaly (problem code). Possible values:
no_tm     = no telemetry at all (WEC off, missing data, etc)
bad_tm    = digital problems, like chopped up data
bad_data  = data formats OK, but data is crap for analog reasons,
            e.g. latched probes, strange guard voltage, hanging sweeps, ...
bad_lx    = LX data is bad, but HX data is OK
bad_hx    = HX data is bad, but LX data is OK
spec_bias = commanded intervals with unusual bias, not accidents
            setting guard to strange values etc which goes to bad_data
bad_bias  = intervals with accidental unusual bias
no_bm3    = No BM3 telemetry
no_p[1-4] = No/bad data on probes [1-4]
no_p[12/32/34] = No/bad data on probe pairs [12/32/34]
hxonly    = HXONLY sampling mode
no_10Hz_filt = 10Hz filter is not operational
no_spin_fits = No on-board spin fits
info      = informational only (no effect on CAA processing)
TBD       = TBD
Effect on the CAA processing:
              no_tm: informational
 bad_tm or bad_data: data is treated as non-existent. No processing performed, no L0 data.
              no_p*: if present, data is blanked from L1.
 bad_bias or bad_hx: E-field data is processed to L0 only. No science E data processed.
   hxonly or bad_lx: P data is processed to L0 only. No science P data processed.
          spec_bias: data is flagged with NSOPS flag
 no_10Hz_filt, no_spin_fits, TBD, info: informational
 -->
<table>
	<title>Cluster EFW Operations</title>
	<description>
		This list is intended to cover all non-standard operations of EFW,
		planned or accidental, from 2001-02-01.
	</description>
	<operation start="2001-02-23T05:18:00Z" dt="11700" c1="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-02-23T05:27:00Z" dt="11160" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-02-25T23:26:00Z" dt="2640" c1="yes" plan="no" sdesc="bad_data">
		<desc>Bad timing of eclipse bias current change.</desc>
	</operation>
	<operation start="2001-02-26T06:10:00Z" dt="12960" c1="yes" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-05T02:42:00Z" dt="2520" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Eclipse.</desc>
	</operation>
	<operation start="2001-03-09T20:58:00Z" dt="2340" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Eclipse.</desc>
	</operation>
	<operation start="2001-03-12T12:16:00Z" dt="9240" c1="yes" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-16T11:59:00Z" dt="14160" c1="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-16T11:59:00Z" dt="18540" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-17T09:20:00Z" dt="13260" c1="yes" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-19T00:18:00Z" dt="10920" c1="yes" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-22T02:48:00Z" dt="3120" c1="yes" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-22T03:40:00Z" dt="99660" c2="yes" plan="no" sdesc="no_tm">
		<desc>Miscommanded burst caused NULL sampling mode.</desc>
		<res>
		<link href="aie010322ax.txt">Anders 010322</link>
		<link href="esoc010323ad.txt">Anders 010323</link>
		</res>
	</operation>
	<operation start="2001-03-22T03:40:00Z" dt="10260" c1="yes" plan="no" sdesc="no_tm">
		<desc>Miscommanded burst caused NULL sampling mode.</desc>
		<res>
		<link href="aie010322ax.txt">Anders 010322</link>
		<link href="esoc010323ad.txt">Anders 010323</link>
		</res>
	</operation>
	<operation start="2001-03-22T03:40:00Z" dt="113460" c4="yes" plan="no" sdesc="no_tm">
		<desc>Miscommanded burst caused NULL sampling mode.</desc>
		<res>
		<link href="aie010322ax.txt">Anders 010322</link>
		<link href="esoc010323ad.txt">Anders 010323</link>
		</res>
	</operation>
	<operation start="2001-03-22T03:40:00Z" dt="118740" c3="yes" plan="no" sdesc="no_tm">
		<desc>Miscommanded burst caused NULL sampling mode.</desc>
		<res>
		<link href="aie010322ax.txt">Anders 010322</link>
		<link href="esoc010323ad.txt">Anders 010323</link>
		</res>
	</operation>
	<operation start="2001-03-23T20:06:00Z" dt="6240" c2="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-03-31T06:35:00Z" dt="1380" c1="yes" c2="yes" c3="yes" c4="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-04-12T11:00:00Z" dt="60600" c4="yes" plan="no" sdesc="hxonly">
		<desc>HXONLY sampling mode.</desc>
	</operation>
	<operation start="2001-04-18T07:30:00Z" dt="300" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Atitude manoeuvre.</desc>
	</operation>
	<operation start="2001-04-18T09:00:00Z" dt="300" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Atitude manoeuvre.</desc>
	</operation>
	<operation start="2001-04-18T12:00:00Z" dt="240" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Atitude manoeuvre.</desc>
	</operation>
	<operation start="2001-04-21T21:30:00Z" dt="11100" c1="yes" c3="yes" c4="yes" plan="no" sdesc="info">
		<desc>Very bad data due to high density.</desc>
	</operation>
	<operation start="2001-05-10T18:04:20Z" dt="70" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Axial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-13T11:13:00Z" dt="4020" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Radial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-13T14:28:00Z" dt="2220" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Radial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-16T22:46:00Z" dt="1680" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Radial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-17T12:56:00Z" dt="360" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Radial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-17T17:27:00Z" dt="2100" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Radial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-21T23:51:00Z" dt="180" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Axial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-05-25T02:11:30Z" dt="80" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Axial delta-v manoeuvre.</desc>
	</operation>
	<operation start="2001-07-15T22:59:00Z" dt="357360" c4="yes" plan="no" sdesc="bad_data">
		<desc>Numerous problems as explained in resource e-mails.</desc>
		<res>
			<link href="pal010727ox.txt">Per-Arne 010727</link>
			<link href="ky010727ox.txt">Keith 010727</link>
		</res>
	</operation>
	<operation start="2001-07-16T21:45:00Z" dt="240" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre.</desc>
	</operation>
	<operation start="2001-07-17T01:00:00Z" dt="240" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre.</desc>
	</operation>
	<operation start="2001-07-17T07:15:00Z" dt="260" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre.</desc>
	</operation>
	<operation start="2001-07-23T13:54:17Z" dt="-1" c2="yes" plan="no" sdesc="no_10Hz_filt">
		<desc>The 10Hz filter on probe 3 failed at this time, and has never recovered.</desc>
	</operation>
	<operation start="2001-07-30T02:55:00Z" dt="3600" c4="yes" plan="no" sdesc="hxonly">
		<desc>HXONLY sampling mode.</desc>
	</operation>
	<operation start="2001-08-15T03:07:03Z" dt="2" c2="yes" plan="no" sdesc="bad_tm">
		<desc>Single bad HX packet.</desc>
	</operation>
	<operation start="2001-09-05T13:52:00Z" dt="4320" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Eclipse.</desc>
	</operation>
	<operation start="2001-10-01T07:30:00Z" dt="2100"
			c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="no_spin_fits">
		<desc>Verify sweep interval settings. Will cause loss of spin fits for 25 minutes.
			07:30 After reset at start of AI, do not uplink spin patch or set burst. Start sweeps every 30 s (SC1), 1
			min (SC2), 90 s (SC3), 2 min (SC4). 07:45 Setup burst (SWECJ349). 07:55 Spinfit patch (SWECJ354).
			08:05 Test completed: change sweep interval to 30 mins on all. (SWECJ340 and 339).</desc>
		<res>
			<link href="010913_aie_iw.txt">Ieuan</link>
		</res>
	</operation>
	<operation start="2001-10-11T12:34:41Z" dt="1258" c1="yes" plan="no" sdesc="no_tm">
		<desc>TM loss due to s/c anomaly</desc>
		<res>
			<link href="esoc011012.txt">ESOC 011012</link>
			<link href="esoc011015.txt">ESOC 011015</link>
		</res>
	</operation>
	<operation start="2001-10-12T22:39:41Z" dt="2" c3="yes" plan="no" sdesc="bad_tm">
		<desc>Single bad HX packet.</desc>
	</operation>
	<operation start="2001-10-15T01:18:00Z" dt="61030" c1="yes" plan="no" sdesc="bad_data">
		<desc>Probe 1 latched at -68 V, other probes also saturated much of the time, reason unknown.</desc>
		<res>
			<link href="latch011015.txt">Anders 011015</link>
		</res>
	</operation>
	<operation start="2001-10-17T05:48:43Z" dt="90" c1="yes" c2="yes" c3="yes" c4="yes"
			plan="yes" sdesc="no_tm">
		<desc>Time tagged burst operations with 2E+3B components at perigee. Loss of data for a little more than a minute expected.</desc>
		<res>
			<link href="011017_pior_burst.txt">Commented excerpt from PIOR</link>
			<link href="010927_NCW.txt">Mail to Nicole and Milan</link>
		</res>
	</operation>
	<operation start="2001-10-22T19:30:00Z" dt="300" c4="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre.</desc>
	</operation>
	<operation start="2001-10-22T21:15:00Z" dt="300" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre.</desc>
	</operation>
	<operation start="2001-11-06T00:47:00Z" dt="4980" c2="yes" plan="no" sdesc="bad_tm">
		<desc>Bad telemetry, reason unknown.</desc>
	</operation>
	<operation start="2001-11-07T19:59:00Z" dt="2640" c3="yes" plan="yes" sdesc="no_tm">
		<desc>SC3 system reboot. No data during this time.</desc>
		<res>
			<link href="esoc011107.txt">ESOC 011107</link>
			<link href="esoc011108.txt">ESOC 011108</link>
		</res>
	</operation>
	<operation start="2001-11-13T00:20:00Z" dt="65400" c2="yes" plan="no" sdesc="bad_hx">
		<desc>Strange data for unknown reason. EDI high current?</desc>
	</operation>
	<operation start="2001-11-14T18:16:00Z" dt="26880" c1="yes" plan="no" sdesc="no_tm">
		<desc>Data loss due to ESA ground station problem</desc>
		<res>
			<link href="esoc011121.txt">ESOC 011121</link>
		</res>
	</operation>

	<operation start="2001-11-18T06:07:14Z" dt="39496" c2="yes" plan="no" sdesc="no_p1">
		<desc>Probe 1 latched at +68 V. Probe 1 problem cured by EFW reset.</desc>
		<res>
			<link href="pal011120.txt">Per-Arne 011120</link>
			<link href="aie011129.txt">Anders 011129</link>
		</res>
	</operation>
	<operation start="2001-12-11T14:27:00Z" dt="7020" c1="yes" c2="yes" c3="yes" c4="yes" plan="no" sdesc="bad_tm">
		<desc>Bad WEC telemetry, DWP buffer overflow?</desc>
	</operation>
	<operation start="2001-12-13T23:14:00Z" dt="7020" c1="yes" c2="yes" c3="yes" c4="yes" plan="no" sdesc="bad_tm">
		<desc>Bad WEC telemetry, DWP buffer overflow?</desc>
	</operation>
	<operation start="2001-12-28T03:02:57Z" dt="-1" c1="yes" plan="no" sdesc="no_p1">
		<desc>Probe 1 effectively lost from this time.</desc>
		<res>
			<link href="pal020102b.txt">Per-Arne 020102</link>
			<link href="pal020104.txt">Per-Arne 020104</link>
			<link href="ma020108.txt">Mats 020108</link>
		</res>
	</operation>
	<operation start="2001-12-29T20:33:00Z" dt="7140" c4="yes" plan="no" sdesc="bad_tm">
		<desc>Bad WEC telemetry, DWP buffer overflow?</desc>
	</operation>
	<operation start="2002-01-02T06:58:00Z" dt="17040" c2="yes" plan="no" sdesc="no_tm">
		<desc>S/c problem caused data loss</desc>
		<res>
			<link href="esoc020108c.txt">ESOC 020108</link>
		</res>
	</operation>
	<operation start="2002-01-02T13:43:00Z" dt="9480" c2="yes" plan="no" sdesc="no_tm">
		<desc>S/c problem caused data loss</desc>
		<res>
			<link href="esoc020108c.txt">ESOC 020108</link>
		</res>
	</operation>
	<operation start="2002-01-02T14:25:00Z" dt="4500" c1="yes" plan="no" sdesc="spec_bias">
		<desc>Attempts to bring P1 back to working order</desc>
		<res>
			<link href="pal020102a.txt">Per-Arne 020102</link>
		</res>
	</operation>
	<operation start="2002-01-06T08:26:40Z" dt="240" c1="yes" plan="no" sdesc="bad_data">
		<desc>Maneuvre?</desc>
	</operation>
	<operation start="2002-01-06T17:04:00Z" dt="650" c4="yes" plan="no" sdesc="bad_data">
		<desc>Maneuvre?</desc>
	</operation>
	<operation start="2002-01-07T17:36:00Z" dt="77370" c3="yes" plan="no" sdesc="no_tm">
		<desc>WEC latchup. All EFW data lost until 2002-01-08 15:05:30. WEC restarted, EFW data regained</desc>
		<res>
			<link href="ky020108.txt">Keith 020108</link>
		</res>
	</operation>
	<operation start="2002-01-08T09:50:00Z" dt="-157" c1="yes" plan="no" sdesc="no_p2">
		<desc>P2 bias went to 0xB2 (-300 nA), causing saturation at -68 V; later to 0 bias. Probable explanation is timing conflict between regular sweep command and extra bias command for probe 1.</desc>
		<res>
			<link href="pal020109a.txt">Per-Arne 010209</link>
			<link href="pal020109b.txt">Per-Arne 010209</link>
		</res>
	</operation>
	<operation start="2002-01-11T11:45:00Z" dt="230" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
		<res><link href="pal060330.txt">Per-Arne 060330</link></res>
	</operation>
	<operation start="2002-01-11T14:30:00Z" dt="180" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
		<res><link href="pal060330.txt">Per-Arne 060330</link></res>
	</operation>
	<operation start="2002-01-11T17:30:21Z" dt="8" c4="yes" plan="yes" sdesc="bad_data">
		<desc>Spin-up manoeuvre</desc>
		<res><link href="pal060330.txt">Per-Arne 060330</link></res>
	</operation>
	<operation start="2002-01-11T19:59:53Z" dt="11" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Spin-up manoeuvre</desc>
		<res><link href="pal060330.txt">Per-Arne 060330</link></res>
	</operation>
	<operation start="2002-01-18T01:31:00Z" dt="39660" c1="yes" plan="no" sdesc="no_tm">
		<desc>WEC data lost following DWP watchdog reset on SC1.</desc>
		<res>
			<link href="pal020118a.txt">Per-Arne 020118</link>
			<link href="ky020118a.txt">Keith 020118</link>
		</res>
	</operation>
	<operation start="2002-02-13T03:37:48Z" dt="3" c1="yes" plan="no" sdesc="bad_data">
		<desc>Maneuvre?</desc>
	</operation>
	<operation start="2002-02-15T18:55:00Z" dt="604800" c1="yes" plan="yes" sdesc="no_p2">
	<desc>P2 in bias voltage (Langmuir) mode for a week from this time</desc>
		<res>
			<link href="aie020125b.txt">Anders 020125</link>
		</res>
	</operation>
	<operation start="2002-02-17T21:45:00Z" dt="1500" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Bias current +16 nA during perigee passes.</desc>
		<res>
			<link href="aie020125b.txt">Anders 020125</link>
		</res>
	</operation>
	<operation start="2002-02-17T22:00:00Z" dt="120" c3="yes" plan="yes" sdesc="spec_bias">
		<desc>Test different bias currents at perigee eclipse.</desc>
		<res>
			<link href="aie020125b.txt">Anders 020125</link>
			<link href="aie020125a.txt">Anders 020125</link>
		</res>
	</operation>
	<operation start="2002-02-20T06:43:00Z" dt="2100" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Bias current +16 nA during perigee passes.</desc>
		<res>
			<link href="aie020125b.txt">Anders 020125</link>
		</res>
	</operation>
	<operation start="2002-02-22T15:43:00Z" dt="-157" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Bias current +16 nA during perigee passes.</desc>
		<res>
			<link href="aie020125b.txt">Anders 020125</link>
		</res>
	</operation>
	<operation start="2002-03-20T09:59:00Z" dt="85440" c2="yes" plan="yes" sdesc="no_tm">
		<desc>CTU switchover on SC2 caused loss of all science data.</desc>
		<res>
			<link href="ms020320.txt">ESOC 020320</link>
			<link href="sm020321.txt">ESOC 020321</link>
		</res>
	</operation>
	<operation start="2002-04-16T09:00:00Z" dt="240" c3="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
		<res><link href="pal060331a.txt">Per-Arne 060331</link></res>
	</operation>
	<operation start="2002-04-16T13:00:00Z" dt="240" c4="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
		<res><link href="pal060331b.txt">Per-Arne 060331</link></res>
	</operation>
	<operation start="2002-04-29T09:55:00Z" dt="772560" c3="yes" plan="no" sdesc="bad_tm">
		<desc>WEC science telemetry bit error capable of causing all sorts of problems: timing jumps, apparent switches in EFW burst data, glitches.</desc>
		<res>
			<link href="ky020612.txt">Keith 020612</link>
		</res>
	</operation>
	<operation start="2002-05-08T08:31:00Z" dt="2280" c3="yes" plan="yes" sdesc="no_tm">
		<desc>WEC power cycled to clear up DWP memory latchup</desc>
		<res>
			<link href="ky020507a.txt">Keith 020507</link>
			<link href="sm020508a.txt">Silvano 020508</link>
		</res>
	</operation>
	<operation start="2002-05-12T03:53:57Z" dt="1800" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Bias test, running -70 nA to all spheres</desc>
		<res>
			<link href="aie020423a.txt">Anders 020423</link>
			<link href="aie020423b.txt">Anders 020423</link>
		</res>
	</operation>
	<operation start="2002-05-26T10:27:00Z" dt="54180" c3="yes" plan="yes" sdesc="spec_bias">
		<desc>Corrupted WEC TM triggered s/c to reset WEC 020526 10:27. EFW then operated with default settings (e.g. non-ideal bias) until 020527 01:30.</desc>
		<res>
			<link href="pal020527a.txt">Per-Arne 020527</link>
			<link href="sm020527a.txt">Silvano 020527</link>
		</res>
	</operation>
	<operation dt="2" plan="no" sdesc="bad_tm" start="2002-06-14T15:02:04Z" c4="yes">
		<desc>Single bad EFW TM packet</desc>
		<res><link href="pal060322a.txt">Per-Arne 060322</link></res>
	</operation>
	<operation dt="3120" plan="no" sdesc="bad_data" start="2002-06-19T09:42:00Z" c3="yes">
		<desc>Spacecraft manoeuvre contaminates data.</desc>
	</operation>
	<operation start="2002-06-29T05:05:00Z" dt="180" c4="yes" plan="no" sdesc="no_tm">
		<desc>EFW telemetry completely confused.</desc>
		<res>
			<link href="sm020704.txt">Silvano 020704</link>
			<link href="aie020704a.txt">Anders 020704</link>
			<link href="ky020710a.txt">Keith 020710</link>
		</res>
	</operation>
	<operation start="2002-07-29T09:06:59Z" dt="-1" c3="yes" plan="no" sdesc="no_p1">
		<desc>Probe 1 effectively lost from this time.</desc>
		<res>
			<link href="pal020806a.txt">Per-Arne 020806</link>
		</res>
	</operation>
	<operation start="2002-08-06T14:10:00Z" dt="1200" c2="yes" c3="yes" plan="yes" sdesc="bad_tm">
		<desc>WBD noise test</desc>
		<res>
			<link href="pal060323a.txt">Per-Arne 060323</link>
		</res>
	</operation>
	<operation start="2002-08-06T18:20:00Z" dt="10800" c1="yes" c2="yes" c3="yes" c4="yes" plan="no" sdesc="bad_tm">
		<desc>BM1 data intermittent (period about 20 s ???) due to wrong STAFF SA mode (TM overflow).</desc>
		<res>
			<link href="ky020808a.txt">Keith 020808</link>
			<link href="pal020821a.txt">Per-Arne 020821</link>
		</res>
	</operation>
	<operation start="2002-08-10T05:34:13Z" dt="194147" c2="yes" plan="no" sdesc="bad_tm">
		<desc>Latchup, SEU protection on ADC trigged, causing complete loss of data until power on/off cycle.</desc>
		<res><link href="pal020812a.txt">Per-Arne 020812</link>
		</res>
	</operation>
	<operation dt="49560" plan="no" sdesc="bad_tm" start="2002-08-13T01:47:00Z" c2="yes">
		<desc>Strange bias sweep behaviour: sweeps take longer and longer time, the last one (at 15:19:20) takes 45 s. They are flagged as sweeps or playbacks only for the nominal time (1-2 s), and hence some HX data are contaminated</desc>
		<res><link href="pal021217svep.txt">Per-Arne 021217</link></res>
	</operation>
	<operation start="2002-08-16T01:10:00Z" dt="51300" c3="yes" plan="no" sdesc="no_tm">
		<desc>SC3 science and HK data lost due to s/c anomaly</desc>
		<res>
			<link href="sm020823a.txt">Silvano 020823</link>
		</res>
	</operation>
	<operation start="2002-08-29T22:52:00Z" dt="59880" c2="yes" plan="no" sdesc="no_tm">
		<desc>SC2 reebooted by mistake at 22:5WEC not fully recovered until the end of a BM1 period at 2002-08-30 15:30.</desc>
		<res>
			<link href="jv020830a.txt">ESOC 020830</link>
			<link href="sm020830a.txt">Silvano 020830</link>
			<link href="ky020902a.txt">Keith 020902</link>
		</res>
	</operation>
	<operation start="2002-08-30T03:30:00Z" dt="8400" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-08-30T14:56:00Z" dt="19380" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-08-30T21:08:00Z" dt="1920" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-08-30T23:00:00Z" dt="3600" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-08-31T00:00:00Z" dt="7200" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-08-31T00:02:12Z" dt="7680" c4="yes" plan="no" sdesc="no_tm">
		<desc>Data loss for s/c reasons.</desc>
		<res>
			<link href="esoc020914a.txt">ESOC 020914</link>
		</res>
	</operation>
	<operation start="2002-09-21T01:18:00Z" dt="11340" c1="yes" plan="no" sdesc="bad_tm">
		<desc>S/c problem caused loss of sun reference pulse and thus scrambling of WEC data. The EFW onboard spinfits should be crazy, as there is no sun pulse.</desc>
		<res>
			<link href="sm020922a.txt">Silvano 020922</link>
	<link href="ky020923a.txt">Keith 020923</link>
		</res>
	</operation>
	<operation start="2002-10-02T00:49:00Z" dt="37080" c4="yes" plan="no" sdesc="no_tm">
		<desc>EFW data scrambled, though analog signals to WHISPER and STAFF are all right. Presumably a radiation induced SEU.</desc>
		<res>
			<link href="pal021002a.txt">Per-Arne 021002</link>
			<link href="sm021004a.txt">Silvano 021004</link>
			<link href="pal021006a.txt.txt">Per-Arne 021006</link>
		</res>
	</operation>
	<operation start="2002-10-02T16:00:00Z" dt="34200" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="info">
		<desc>Testing the FGM burst trig flag</desc>
		<res>
			<link href="aie020910a.txt">Anders 020910</link>
			<link href="aie020910b.txt">Anders 020910</link>
			<link href="aie021104.txt">Anders 021104</link>
		</res>
	</operation>
	<operation start="2002-10-05T02:30:00Z" dt="23400" c1="yes" c2="yes" c3="yes" c4="yes" plan="yes" sdesc="info">
		<desc>Testing the FGM burst trig flag</desc>
		<res>
			<link href="aie020910a.txt">Anders 020910</link>
			<link href="aie020910b.txt">Anders 020910</link>
			<link href="aie021104.txt">Anders 021104</link>
		</res>
	</operation>
	<operation start="2002-10-07T19:00:00Z" dt="300" c2="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
	</operation>
	<operation start="2002-10-07T20:00:00Z" dt="300" c4="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
	</operation>
	<operation start="2002-10-07T22:45:00Z" dt="300" c1="yes" plan="yes" sdesc="bad_data">
		<desc>Attitude manoeuvre</desc>
	</operation>
	<operation start="2002-10-10T14:07:00Z" dt="77460" c3="yes" plan="no" sdesc="no_tm">
		<desc>WEC turned off by SC after DWP voltage flag = 0xFF.</desc>
		<res>
			<link href="sm021011a.txt">Silvano 021011</link>
			<link href="sm021011b.txt">Silvano 021011</link>
		</res>
	</operation>
	<operation start="2002-10-20T00:52:28Z" dt="746" c3="yes" plan="no" sdesc="no_tm">
		<desc>Ground station problems caused data loss.</desc>
		<res>
			<link href="esoc021022.txt">ESOC 021022</link>
		</res>
	</operation>
	<operation start="2002-10-20T13:21:52Z" dt="75345" c4="yes" plan="no" sdesc="no_tm">
		<desc>WEC turned off by s/c</desc>
		<res>
			<link href="sm021021a.txt">Silvano 021021</link>
			<link href="ky021021a.txt">Keith 021021</link>
			<link href="sm021021b.txt">Silvano 021021</link>
			<link href="ky021021b.txt">Keith 021021</link>
		</res>
	</operation>
	<operation start="2002-10-21T02:32:17Z" dt="4106" c3="yes" plan="no" sdesc="no_tm">
		<desc>Ground station problems caused data loss.</desc>
		<res>
			<link href="esoc021022.txt">ESOC 021022</link>
		</res>
	</operation>
	<operation start="2002-10-28T03:00:00Z" dt="-157" c2="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Two-minute bias current sweeps using internal burst at 450 S/s</desc>
		<res>
			<link href="aie021009a.txt">Anders 021009</link>
			<link href="aie021009b.txt">Anders 021009</link>
		</res>
	</operation>
	<operation start="2002-10-29T13:00:00Z" dt="-157"  c2="yes" c4="yes" plan="yes" sdesc="spec_bias">
		<desc>Two-minute bias current sweeps using internal burst at 450 S/s</desc>
		<res>
			<link href="aie021009a.txt">Anders 021009</link>
			<link href="aie021009b.txt">Anders 021009</link>
		</res>
	</operation>
	<operation start="2002-11-01T21:23:00Z" dt="11820" c1="yes" c3="yes"  plan="no" sdesc="info">
		<desc>By mistake, the failed P1 on SC13 were in E-field mode. This causes the flight s/w to use P12 for calcultating Vsc for HK and IEL, which thus are bad. Science data are OK.</desc>
		<res>
			<link href="aie021106a.txt">Anders 021106</link>
		</res>
	</operation>
	<operation start="2002-11-02T01:33:00Z" dt="87060" c1="yes" c3="yes" plan="no" sdesc="info">
	<desc>By mistake, the failed P1 on SC13 were in E-field mode. This causes the flight s/w to use P12 for calcultating Vsc for HK and IEL, which thus are bad. Science data are OK.</desc>
		<res>
			<link href="aie021106a.txt">Anders 021106</link>
		</res>
	</operation>
	<operation start="2002-11-03T04:23:00Z" dt="109080" c3="yes" plan="no" sdesc="no_tm">
	<desc>WEC problems probably due to SEUs in DWP.</desc>
		<res>
			<link href="sm021104a.txt">Silvano 021104</link>
			<link href="ky021105b.txt">Keith 021105</link>
		</res>
	</operation>
	<operation start="2002-11-03T13:34:00Z" dt="77580" c1="yes" plan="no" sdesc="no_tm">
		<desc>WEC problems probably due to SEUs in DWP.</desc>
		<res>
			<link href="sm021104a.txt">Silvano 021104</link>
			<link href="ky021105b.txt">Keith 021105</link>
		</res>
	</operation>
	<operation start="2002-11-05T08:27:00Z" dt="20" c2="yes" plan="no" sdesc="bad_tm">
		<desc>ADCE switchover on SC2.</desc>
		<res>
			<link href="esoc021106a.txt">ESOC 021106</link>
			<link href="ky021107.txt">Keith 021107</link>
		</res>
	</operation>
	<operation start="2002-11-05T08:27:20Z" dt="820" c2="yes" plan="no" sdesc="bad_data">
		<desc>Uncontrolled manoeuvre</desc>
		<res><link href="pal060331c.txt">Per-Arne 060331</link></res>
	</operation>
	<operation start="2002-11-12T01:53:00Z" dt="840" c3="yes"  plan="no" sdesc="no_tm">
		<desc>Spacecraft anomaly caused scrambled and lost science data.</desc>
		<res>
			<link href="ky021115a.txt">Keith 021115</link>
			<link href="esoc021115a.txt">ESOC 021115</link>
		</res>
	</operation>
	<operation start="2002-11-12T04:24:00Z" dt="28740" c3="yes"  plan="no" sdesc="no_tm">
		<desc>Spacecraft anomaly caused scrambled and lost science data.</desc>
		<res>
			<link href="ky021115a.txt">Keith 021115</link>
			<link href="esoc021115a.txt">ESOC 021115</link>
		</res>
	</operation>
	<operation start="2002-11-12T23:56:24Z" dt="40" c2="yes" plan="no" sdesc="no_p3">
		<desc>P3 stuck after a sweep.</desc>
	</operation>
	<operation start="2002-11-13T02:34:27Z" dt="21" c2="yes" plan="no" sdesc="no_p3">
		<desc>P3 stuck after a sweep.</desc>
	</operation>
	<operation start="2002-11-13T03:13:58Z" dt="43" c2="yes" plan="no" sdesc="no_p3">
		<desc>P3 stuck after a sweep.</desc>
	</operation>
	<operation start="2002-11-13T04:32:59Z" dt="33" c2="yes" plan="no" sdesc="no_p3">
		<desc>P3 stuck after a sweep.</desc>
	</operation>
	<operation start="2002-11-13T05:52:01Z" dt="24" c2="yes" plan="no" sdesc="no_p3">
		<desc>P3 stuck after a sweep.</desc>
	</operation>
	<operation start="2002-11-15T03:27:00Z" dt="100080" c2="yes"  plan="no" sdesc="bad_tm">
		<desc>C2 is bad after a spontanous EFW reset.</desc>
		<res><link href="pal060405a.txt">Per-Arne 060405</link></res>
	</operation>
	<operation dt="6060" plan="no" sdesc="no_tm" start="2002-11-21T17:01:00Z" c1="yes">